get http://localhost:8080/app

###

get http://localhost:8080/app/assets

###

get http://localhost:8080/admin/metrics


###

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "hello there"
}

###

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "hello there.
    The newline will cause an error"
}

###

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "hello there. this is gonna be a super long string. certainly over 140 characters. Francois is so cute. I love Jalen Brunson. Go Knicks. You better not validate my chirp."
}

###

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this has kerfuffle profanity"
}

###

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this does not have kerfuffle! profanity"
}

###

post http://localhost:8080/api/validate_chirp

###

post http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "cooper@example.com"
}

###

post http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "saul@bettercall.com"
}

###

post http://localhost:8080/admin/reset


###

post http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "This is a chirp",
    "user_id": "7cc32efe-4af8-45af-b6c6-fb793c9722b7"
}